"""WS 协议常量,与 server/internal/model/opcodes.go 保持一致。"""

OP_DISPATCH = 0
OP_HEARTBEAT = 1
OP_IDENTIFY = 2
OP_SET_ACTIVE_CONV = 3
OP_RESUME = 6
OP_RECONNECT = 7
OP_HELLO = 10
OP_HEARTBEAT_ACK = 11
OP_PLUGIN_CALL = 12
OP_PLUGIN_RESULT = 13
OP_STREAM = 14

EVENT_MESSAGE_CREATE = "MESSAGE_CREATE"
EVENT_MESSAGE_UPDATE = "MESSAGE_UPDATE"
EVENT_MESSAGE_DELETE = "MESSAGE_DELETE"
EVENT_MESSAGE_READ = "MESSAGE_READ"
EVENT_TYPING_START = "TYPING_START"
EVENT_GENERATION_ABORT = "GENERATION_ABORT"
EVENT_CONVERSATION_UPDATE = "CONVERSATION_UPDATE"
EVENT_CONVERSATION_PARTICIPANT_JOIN = "CONVERSATION_PARTICIPANT_JOIN"
EVENT_CONVERSATION_PARTICIPANT_LEAVE = "CONVERSATION_PARTICIPANT_LEAVE"
EVENT_SESSION_META_UPDATE = "SESSION_META_UPDATE"
EVENT_AGENT_ONLINE = "AGENT_ONLINE"
EVENT_AGENT_OFFLINE = "AGENT_OFFLINE"
EVENT_APPROVAL_DECIDED = "APPROVAL_DECIDED"
EVENT_APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
EVENT_AGENT_MODELS = "AGENT_MODELS"
EVENT_AGENT_SLASH_CATALOG = "AGENT_SLASH_CATALOG"
EVENT_PLUGIN_CAPABILITIES = "PLUGIN_CAPABILITIES"
EVENT_FRIEND_REQUEST_RECEIVED = "FRIEND_REQUEST_RECEIVED"
EVENT_FRIEND_REQUEST_DECIDED = "FRIEND_REQUEST_DECIDED"
EVENT_FRIEND_REMOVED = "FRIEND_REMOVED"
EVENT_STREAM = "STREAM"
