from wanling_sdk.opcodes import (
    EVENT_AGENT_MODELS,
    EVENT_AGENT_OFFLINE,
    EVENT_AGENT_ONLINE,
    EVENT_AGENT_SLASH_CATALOG,
    EVENT_APPROVAL_DECIDED,
    EVENT_APPROVAL_EXPIRED,
    EVENT_CONVERSATION_PARTICIPANT_JOIN,
    EVENT_CONVERSATION_PARTICIPANT_LEAVE,
    EVENT_CONVERSATION_UPDATE,
    EVENT_FRIEND_REMOVED,
    EVENT_FRIEND_REQUEST_DECIDED,
    EVENT_FRIEND_REQUEST_RECEIVED,
    EVENT_GENERATION_ABORT,
    EVENT_MESSAGE_CREATE,
    EVENT_MESSAGE_DELETE,
    EVENT_MESSAGE_READ,
    EVENT_MESSAGE_UPDATE,
    EVENT_PLUGIN_CAPABILITIES,
    EVENT_SESSION_META_UPDATE,
    EVENT_STREAM,
    EVENT_TYPING_START,
    OP_DISPATCH,
    OP_HEARTBEAT,
    OP_HEARTBEAT_ACK,
    OP_HELLO,
    OP_IDENTIFY,
    OP_PLUGIN_CALL,
    OP_PLUGIN_RESULT,
    OP_RECONNECT,
    OP_RESUME,
    OP_SET_ACTIVE_CONV,
    OP_STREAM,
)


def test_opcodes_align_with_server():
    assert OP_DISPATCH == 0
    assert OP_HEARTBEAT == 1
    assert OP_IDENTIFY == 2
    assert OP_SET_ACTIVE_CONV == 3
    assert OP_RESUME == 6
    assert OP_RECONNECT == 7
    assert OP_HELLO == 10
    assert OP_HEARTBEAT_ACK == 11
    assert OP_PLUGIN_CALL == 12
    assert OP_PLUGIN_RESULT == 13
    assert OP_STREAM == 14


def test_events_align_with_server():
    assert EVENT_MESSAGE_CREATE == "MESSAGE_CREATE"
    assert EVENT_MESSAGE_UPDATE == "MESSAGE_UPDATE"
    assert EVENT_MESSAGE_DELETE == "MESSAGE_DELETE"
    assert EVENT_MESSAGE_READ == "MESSAGE_READ"
    assert EVENT_TYPING_START == "TYPING_START"
    assert EVENT_GENERATION_ABORT == "GENERATION_ABORT"
    assert EVENT_CONVERSATION_UPDATE == "CONVERSATION_UPDATE"
    assert EVENT_CONVERSATION_PARTICIPANT_JOIN == "CONVERSATION_PARTICIPANT_JOIN"
    assert EVENT_CONVERSATION_PARTICIPANT_LEAVE == "CONVERSATION_PARTICIPANT_LEAVE"
    assert EVENT_SESSION_META_UPDATE == "SESSION_META_UPDATE"
    assert EVENT_AGENT_ONLINE == "AGENT_ONLINE"
    assert EVENT_AGENT_OFFLINE == "AGENT_OFFLINE"
    assert EVENT_APPROVAL_DECIDED == "APPROVAL_DECIDED"
    assert EVENT_APPROVAL_EXPIRED == "APPROVAL_EXPIRED"
    assert EVENT_AGENT_MODELS == "AGENT_MODELS"
    assert EVENT_AGENT_SLASH_CATALOG == "AGENT_SLASH_CATALOG"
    assert EVENT_PLUGIN_CAPABILITIES == "PLUGIN_CAPABILITIES"
    assert EVENT_FRIEND_REQUEST_RECEIVED == "FRIEND_REQUEST_RECEIVED"
    assert EVENT_FRIEND_REQUEST_DECIDED == "FRIEND_REQUEST_DECIDED"
    assert EVENT_FRIEND_REMOVED == "FRIEND_REMOVED"
    assert EVENT_STREAM == "STREAM"
